redis:
  host: localhost
  port: 6379
  geoCalcRadius: 10.0
  key: "APP"

output:
  folder: "/home/joao/IdeaProjects/geochallenge/out/"
  file: "output.csv.gz"

data:
  folder: "data/"
  file: "optd-sample-20161201.csv.gz"

input:
  folder: "input/"
  file: "sample_data.csv.gz"